#
# MAINTAINER        henry <henry@miniants@cn>
# DOCKER-VERSION    1.6.2
#
# Dockerizing TOMCAT: Dockerfile for building TOMCAT images
#

FROM       miniants/tomcat:8.0.30
MAINTAINER henry <henry@miniants@cn>
