#
# MAINTAINER        henry <henry@miniants@cn>
# DOCKER-VERSION    1.6.2
#
# Dockerizing TOMCAT: Dockerfile for building TOMCAT images
#

FROM       registry.aliyuncs.com/miniants/tomcat:6.0.45
MAINTAINER henry <henry@miniants@cn>
